#!/bin/sh
#. /etc/profile.d/lang.sh
#. ~/.profile
#. /etc/X11/xinit/xinitrc-common

if [[ -f ~/.Xresources ]]; then
	xrdb -load ~/.Xresources && echo "loaded Xresources"
fi

#unset LC_ALL
#export LANG=en_US.UTF-8
#export LC_MESSAGES=C
# export LC_TIME=en_DK.UTF-8

# Disable DPMS turning off the screen
#xset -dpms
#xset s off

# Disable bell
xset -b

# Mouse
xset m 1/1 0
if xinput query-state "Primax Kensington Eagle Trackball" > /dev/null; then
	xinput set-prop "Primax Kensington Eagle Trackball" "libinput Accel Profile Enabled" 0, 1
	xinput set-prop "Primax Kensington Eagle Trackball" "libinput Accel Speed" -0.25
fi
if xinput query-state "Kensington Slimblade Trackball" > /dev/null; then
	xinput set-prop "Kensington Slimblade Trackball" "libinput Accel Profile Enabled" 0, 1
	xinput set-prop "Kensington Slimblade Trackball" "libinput Accel Speed" -0.20
	xinput set-button-map "Kensington Slimblade Trackball" 1 8 3 4 5 6 7 2
fi


# Enable zapping (C-A-<Bksp> kills X)
setxkbmap -option terminate:ctrl_alt_bksp
#setxkbmap -option caps:escape
setxkbmap -layout "us,us" -variant ",intl"
setxkbmap -option "grp:alt_shift_toggle"

# Set background color
xsetroot -gray -bg "#1d2021" -fg "#000000"

# Enable core dumps in case something goes wrong
#ulimit -c unlimited

